// slug → 中文名
// 译名参考: 国内中字版奥特曼/百度百科, 命名以简短为主
// 翻译不准或想换的, 直接改这里即可, 不用动 schema 或路由
const CHARACTER_NAME_ZH = {
  // === ultraman (初代) ===
  aboras: '阿博拉斯',
  alienbaltan: '巴尔坦星人',
  alienbaltan2: '巴尔坦星人（二代）',
  alienmefilas: '梅菲拉斯星人',
  alienzarab: '扎拉布星人',
  alienzton: '泽顿',
  antlar: '安东拉',
  banila: '巴尼拉',
  bemlar: '贝姆拉',
  bullton: '布顿',
  chandolar: '钱德勒',
  dada: '达达',
  dodongo: '多多',
  dorako: '多拉考',
  gamakujira: '加马库基拉',
  gango: '甘戈',
  gavadona: '加瓦顿',
  gavadonb: '加瓦顿 B',
  gavora: '加沃拉',
  geronimon: '杰罗尼蒙',
  goldon: '戈尔顿',
  gomora: '哥莫拉',
  greenmons: '绿蒙斯',
  gubila: '古维拉',
  guesra: '格欧斯',
  guigass: '古加',
  hydra: '海德拉',
  imitultraman: '冒牌奥特曼',
  jamilar: '贾米拉',
  jirahs: '基拉',
  kemular: '凯姆尔人',
  kemur2: '凯姆尔人（二代）',
  keronia: '凯洛尼亚',
  keylla: '凯鲁',
  magular: '马格拉',
  mummyman: '木乃伊人',
  neronga: '内隆戈',
  noa: '诺亚',
  pestar: '培斯塔',
  pigmon: '皮古蒙',
  ragonman: '拉贡人',
  redking: '雷德王',
  redking2: '雷德王（二代）',
  redorako: '雷多罗科',
  saigo: '赛格',
  seabozu: '西波祖',
  skydon: '斯凯顿',
  suflan: '萨夫兰',
  suflan2: '萨夫兰（二代）',
  terresdon: '特雷斯顿',
  woo: '武',
  zaragas: '扎拉加斯',
  zoffy: '佐菲',
  zton: '泽顿',
  zumbolar: '赞勃拉',
};

module.exports = { CHARACTER_NAME_ZH };
